### ISSUE TITLE
[Bug]: Migration not found v1.2.0 to v1.2.1

### ISSUE THREAD

**Issue by danner26** [netbox-community/netbox-acls#116]
### NetBox access-list plugin version

1.2.1

### NetBox version

3.4.3

### Steps to Reproduce

Running on a RHEL 8 virtual machine, NetBox is installed via the git method. We were already upgraded to version 3.4.3 of NetBox when running netbox-acls v1.2.0. This morning I upgraded netbox-acls using the `/opt/netbox/upgrade.sh` script (running as root), and the following missing migration warning was presented.

![image](https://user-images.githubusercontent.com/8165027/214670215-5644a455-e10b-4de9-89c3-60ec285a8e4d.png)

### Expected Behavior

It is expected that any migrations needed should have been applied.

### Observed Behavior

A migration error following `No migrations to apply.` stating that `'netbox_acls' have changes that are not yet reflected in a migration`

**Comment by danner26** [comment]
Looks good in v1.2.2! Thank you
![image](https://user-images.githubusercontent.com/8165027/214682781-ddf0d9a3-e10a-45ff-9f31-60325f7594b5.png)

**Comment by ryanmerolle** [comment]
Thanks for bringing to our attention.
