### ISSUE TITLE
[Bug]: AccessList RegexValidator not allowing hyphens

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox-acls#133]
### NetBox access-list plugin version

v1.2.2

### NetBox version

v3.4.3

### Steps to Reproduce

Use the access-list name "test-test"

### Expected Behavior

test-test should succeeded

### Observed Behavior

Error is raised: "Only alphanumeric, hyphens, and underscores characters are allowed."

**Comment by fishdrummer** [comment]
Hi Ryan! As far as I understand, this bug correction is not included in current version 1.3.0.
Is there by any chance a new release planned soon?
Thx!

**Comment by ryanmerolle** [comment]
I swore it was in there, but I will check this afternoon.
