### ISSUE TITLE
[Feature]: NetBox 3.5 Support

### ISSUE THREAD

**Issue by ryanmerolle** [netbox-community/netbox-acls#145]
### NetBox version

v3.5.0

### Feature type

Add a function

### Proposed functionality

Please see [the release notes for 3.5 changes](https://github.com/netbox-community/netbox/releases/tag/v3.5.0)

### Use case

Currently NetBox 3.5 will not run with this plugin installed.

**Comment by pdenessen** [comment]
Confirmed, causes error in update script reporting. Also in V3.5.1

**Comment by andersonit** [comment]
Bump.  Still not working with V3.5.3 and would really like to use this plugin.  Any updates or ETA?  Thanks!

**Comment by abhi1693** [comment]
I'll try to get a basic PR ready for v3.5 this week.

**Comment by ryanmerolle** [comment]
Yea I’ll work with abhi.  I had not heard much noise about this script to update, and personal life was busy.  We are also always happy to take PRs from the community.

**Comment by ryanmerolle** [comment]
PR created and ready for testing.
