### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by metaIhead** [netbox-community/netbox-acls#146]
### NetBox access-list plugin version

v1.2.2

### NetBox version

v3.4.9

### Steps to Reproduce

go to /plugins/access-lists/access-lists/add/
Fill in all fields with an asterisk

### Expected Behavior

Сccess list is created

### Observed Behavior

![изображение](https://github.com/ryanmerolle/netbox-acls/assets/36397154/471ed86e-e5ec-49ba-aea8-aa4513903913)

<class 'netbox_acls.models.access_lists.AccessList.assigned_object_type.RelatedObjectDoesNotExist'>

AccessList has no assigned_object_type.

Python version: 3.8.10
NetBox version: 3.4.9

**Comment by abhi1693** [comment]
This is fixed in NetBox v3.5.1 but the plugin is not yet compatible.
