### ISSUE TITLE
[Bug]: Filtering multiple choices not working

### ISSUE THREAD

**Issue by 3bruno** [netbox-community/netbox-acls#15]
### NetBox access-list plugin version

v0.1

### NetBox version

v3.2.5

### Steps to Reproduce

Hi. When filtering a field that permit multiple choice, only one condition is bringing.

Example: Filter the field "Protocol" (Access List Rules) with choices "TCP and UDP", but is listing only UDP rules.

With no filter:
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/72423012/176899956-755563be-aacb-46ac-bfcf-02d3d28783f1.png">

With filter not working:
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/72423012/176900071-c209d1ef-6b54-4944-8674-961b2120e0d8.png">

### Expected Behavior

Filter both Access List Rules with protocol TCP and UDP.

### Observed Behavior

It's filtering only one option.

**Comment by ryanmerolle** [comment]
Good find!

A bug fix here would be good to also upstream to the forked plugin tutorial.  It could even be a NetBox core bug.

**Comment by ryanmerolle** [comment]
For now I am limiting filtering to single choices to address this.  More because if I introduce bulkedit, selecting rules with varying values would cause some complexity with the logic/validation checks.
