### ISSUE TITLE
[Feature]: Add support for NetBox v3.6

### ISSUE THREAD

**Issue by abhi1693** [netbox-community/netbox-acls#159]
### NetBox version

v3.6

### Feature type

Add a function

### Proposed functionality

Update the plugin as per the NetBox v3.6 release

https://github.com/netbox-community/netbox/pull/13614

### Use case

To support on newer version

**Comment by stuntguy3000** [comment]
@abhi1693 I hate to bump like this, just wondering if you had any updates or ETAs?

I haven't tried compiling this plugin with v3.6 support either - is anything actually broken? I'm happy to give it a shot myself, although I couldn't get the docker instance playing nice.

**Comment by garnser** [comment]
Compile works fine but upon launching netbox it fails on:

```
ImportError: cannot import name 'ChoiceField' from 'utilities.forms.fields' (/opt/netbox/netbox/utilities/forms/fields/__init__.py)
[ Use DB_WAIT_DEBUG=1 in netbox.env to print full traceback for errors here ]
⏳ Waiting on DB... (0s / 30s)
```

**Comment by kamlesh0606** [comment]
Any update on it?

**Comment by garnser** [comment]
Gave this a spin and it worked for Netbox 3.7
https://github.com/netbox-community/netbox-acls/pull/175
