### ISSUE TITLE
[Bug]: Add support for NetBox v3.7

### ISSUE THREAD

**Issue by slippern1** [netbox-community/netbox-acls#176]
### NetBox access-list plugin version

v1.3.0

### NetBox version

v3.7.2

### Steps to Reproduce

Install plugin on Netbox 3.7.2

### Expected Behavior

Added support for Netbox 3.7.2

### Observed Behavior

gunicorn[21389]: django.core.exceptions.ImproperlyConfigured: Plugin netbox_acls requires NetBox maximum version 3.5.99.
gunicorn[21389]:     raise ImproperlyConfigured(
gunicorn[21389]:   File "/opt/netbox/netbox/netbox/plugins/__init__.py", line 141, in validate
gunicorn[21389]:     plugin_config.validate(PLUGINS_CONFIG[plugin_name], VERSION)
gunicorn[21389]:   File "/opt/netbox/netbox/netbox/settings.py", line 799, in <module>
gunicorn[21389]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
gunicorn[21389]:   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
gunicorn[21389]:   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
gunicorn[21389]:   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
gunicorn[21389]:   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
gunicorn[21389]:   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
gunicorn[21389]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn[21389]:     return _bootstrap._gcd_import(name[level:], package, level)
gunicorn[21389]:   File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
gunicorn[21389]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by jsenecal** [comment]
Closing this one in favor of the better documented and more recent #177

**Comment by jsenecal** [comment]
Closing this one in favor of the better documented and more recent #177
