### ISSUE TITLE
[Bug]: Unable to download v1.4.0

### ISSUE THREAD

**Issue by jairoito** [netbox-community/netbox-acls#185]
### NetBox access-list plugin version

v1.4.0

### NetBox version

v3.6.5

### Steps to Reproduce

source /opt/netbox/venv/bin/activate
(venv) ubuntu@ip-172-31-1-111:~$ sudo pip install netbox-acls==1.4.0
ERROR: Could not find a version that satisfies the requirement netbox-acls==1.4.0 (from versions: 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.2.2, 1.3.0)
ERROR: No matching distribution found for netbox-acls==1.4.0

### Expected Behavior

Download and install version 1.4.0

### Observed Behavior

Error says version 1.4.0 is not available

**Comment by giffordjim** [comment]
It appears you have to using python 3.10 or greater to use this plugin from version 1.4.0 and up. Not sure if that is right.

**Comment by jeffgdotorg** [comment]
@jairoito cannot reproduce. I think this was a transient issue around timing. Please open a new bug if you continue to experience this problem.
