### ISSUE TITLE
[Housekeeping]: Fix target branch name in PR template

### ISSUE THREAD

**Issue by jeffgdotorg** [netbox-community/netbox-acls#188]
### Proposed Changes

Correct the suggested target branch name in the repo's PR template to read `dev` rather than `devel`

### Justification

The current wording of the PR template does not match the project's current branch layout and may be confusing to new contributors

**Comment by jsenecal** [comment]
I see that you submitted and merged a PR for this. Can this issue be closed @jeffgdotorg ?
