### ISSUE TITLE
[Bug]: Querying access list yields error when adding new interface assignment

### ISSUE THREAD

**Issue by cs-1** [netbox-community/netbox-acls#194]
### NetBox access-list plugin version

v1.5.0

### NetBox version

v3.7.5

### Steps to Reproduce

1. Go to Interface Assignments.
2. Add a new assignment.
3. In the Access List field enter a query to search an ACL.

### Expected Behavior

Search displays any ACLs matching the query.

### Observed Behavior

An error is displayed:

> Cannot resolve keyword "description" into field. Choices are: aclextendedrules, aclinterfaceassignment, aclstandardrules, assigned_object, assigned_object_id, assigned_object_type, assigned_object_type_id, bookmarks, comments, created, custom_field_data, default_action, device, id, journal_entries, last_updated, name, tagged_items, tags, type, virtual_chassis, virtual_machine

This error is due to an invalid query in

https://github.com/netbox-community/netbox-acls/blob/685a91bb07c0e54d4a59abee87d8827964ca60ac/netbox_acls/filtersets.py#L79-L83

Access lists don't have a description attribute hence the query fails. I created a pull request https://github.com/netbox-community/netbox-acls/pull/193 which fixes this issue. It also fixes and enhances quick searches for access lists, standard and extended rules as well as for interface assignments.

**Comment by cs-1** [comment]
I'm sorry for issuing the PR before this issue was accepted. Won't happen again. I hope that you'll still consider the PR. I'm rather new to contributing code.

**Comment by cruse1977** [comment]
hey cs - thanks for the pull and don't worry, I'm new to merging :) we've merged in the pull
