### ISSUE TITLE
[Bug]: Access Lists - Result filter not working for VM or device

### ISSUE THREAD

**Issue by curio-scripter** [netbox-community/netbox-acls#195]
### NetBox access-list plugin version

v1.5.0

### NetBox version

v3.7.6

### Steps to Reproduce

Create Access Lists in plugin and associate with specific VM or device. 
Attempt to filter results based on virtual_machines or device filter using UI or with Ansible using netbox.netbox.nb_lookup.

### Expected Behavior

Filter the ACL results and return only relevant VMs or devices.

### Observed Behavior

Does not filter results, returns all ACLs

**Comment by jeffgdotorg** [comment]
I was able to reproduce this bug with a fresh NetBox 4.0.5 installation and ACLs plugin v1.6.0.

Filtering list of ACLs to one Device:
![image](https://github.com/netbox-community/netbox-acls/assets/1209268/ae6a8d20-063a-40a4-9d56-10ef3c083355)

Filtering list of ACLs to one Virtual Machine:
![image](https://github.com/netbox-community/netbox-acls/assets/1209268/d5e6416a-9283-45bf-ad98-f929d7fa8ae6)

**Comment by Julio-Oliveira-Encora** [comment]
Could you please assign it to me?
