### ISSUE TITLE
[Bug]: Version 1.5.0 Not Available

### ISSUE THREAD

**Issue by cameronw1996** [netbox-community/netbox-acls#198]
### NetBox access-list plugin version

v1.5.0

### NetBox version

v3.7.1

### Steps to Reproduce

Adding version 1.5.0 into the requirements list to install plugin on upgrade

### Expected Behavior

verision 1.5.0 installs

### Observed Behavior

Instead, I get this error stating v1.5.0 is not available

```
ERROR: Could not find a version that satisfies the requirement netbox-acls==1.5.0 (from versions: 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.2.2, 1.3.0)
ERROR: No matching distribution found for netbox-acls==1.5.0
```

**Comment by ryanmerolle** [comment]
You likely are using python3.9 1.3.0 is the last release with support for 3.9.  Upgrade your python and this should get resolved.

**Comment by cameronw1996** [comment]
Do you have a handy guide on how best to upgrade python?

**Comment by ryanmerolle** [comment]
You could have deployed netbox in a number of ways I’m not savvy.  I love netbox-docker because it just handles that for me and I got fed up with keeping my system up to date.
