### ISSUE TITLE
[Bug]: Add Support for Netbox Version 4.1.0

### ISSUE THREAD

**Issue by kilian0001** [netbox-community/netbox-acls#208]
### NetBox access-list plugin version

1.6.1

### NetBox version

v4.1.0

### Steps to Reproduce

Upgrade from 4.0.x to 4.1.0. and run manage.py

### Expected Behavior

All Plugins load as normal

### Observed Behavior

When running manage.py it loads all plugins afterwards it gives an error that the version isnt campatible for 4.1.0

**Comment by cruse1977** [comment]
Can you post the errors you see please
