### ISSUE TITLE
[Bug]: GraphQL does not properly constrain on getter

### ISSUE THREAD

**Issue by DanSheps** [netbox-community/netbox-acls#212]
### NetBox access-list plugin version

v1.6.1

### NetBox version

v4.1.1

### Steps to Reproduce

Make a graphql request to plugin requesting a specific object which you don't have permissions to

### Expected Behavior

Denied access

### Observed Behavior

Object returned

**Comment by DanSheps** [comment]
To fix:
schema.py
```diff
-    @strawberry.field
-    def access_list(self, id: int) -> AccessListType:
-        return AccessList.objects.get(pk=id)
+    access_list: AccessListType = strawberry_django.field()
```

```diff
-    @strawberry.field
-    def acl_extended_rule(self, id: int) -> ACLExtendedRuleType:
-        return ACLExtendedRule.objects.get(pk=id)
+    acl_extended_rule: ACLExtendedRuleType = strawberry_django.field()
```

```diff
-    @strawberry.field
-    def acl_standard_rule(self, id: int) -> ACLStandardRuleType:
-        return ACLStandardRule.objects.get(pk=id)
+    acl_standard_rule: ACLStandardRuleType = strawberry_django.field()
```

**Comment by cruse1977** [comment]
`PATCH a single object without permission. ... ok
test_root (netbox_acls.tests.test_api.AppTest.test_root) ... ok

======================================================================
FAIL: test_graphql_get_object (netbox_acls.tests.test_api.ACLTestCase.test_graphql_get_object)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/test/utils.py", line 443, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/netbox/utilities/testing/api.py", line 566, in test_graphql_get_object
    self.assertNotIn('errors', data)
AssertionError: 'errors' unexpectedly found in {'data': None, 'errors': [{'message': "Unknown argument 'id' on field 'Query.access_list'.", 'locations': [{'line': 3, 'column': 29}]}]}

----------------------------------------------------------------------
Ran 22 tests in 0.675s
`
