### ISSUE TITLE
[Bug]: Site is not filtered by site group in add access list form

### ISSUE THREAD

**Issue by abhi1693** [netbox-community/netbox-acls#51]
### NetBox access-list plugin version

1.0.0

### NetBox version

3.2.7

### Steps to Reproduce

1. Go to add access list page
2. Select an existing site group
3. Open the site drop and notice the results
4. Remove the site group selection
5. Open the site drop and notice the results

### Expected Behavior

Sites should be filtered by site group

### Observed Behavior

Full list of site is displayed

**Comment by ryanmerolle** [comment]
Thanks! I'll take a look hopefully this weekend. Also happy to collaborate.

**Comment by abhi1693** [comment]
I'll raise a PR for this today. It's quite an easy fix.
