### ISSUE TITLE
[Bug]: Device filter does not work with region selector

### ISSUE THREAD

**Issue by abhi1693** [netbox-community/netbox-acls#52]
### NetBox access-list plugin version

1.0.0

### NetBox version

3.2.7

### Steps to Reproduce

1. Ensure you have a device in a region first (can be on any site)
2. Open the add access list form
3. Select the region for your device
4. From the list, in the search field, type the partial name. If your device is named (nyc-amk-dev1-sw), type `dev1` in the field
5. Device will not be found

### Expected Behavior

Device should be visible if the selected filters match it's parameters

### Observed Behavior

Device is not found

**Comment by abhi1693** [comment]
Upon inspecting the console

![image](https://user-images.githubusercontent.com/5083532/181905065-513e8d54-bba2-4a37-b934-89eac8c24fae.png)

**Comment by ryanmerolle** [comment]
Thanks!  I'll take a look hopefully this weekend.  Also happy to collaborate.

**Comment by abhi1693** [comment]
I'll raise a PR for this today. It's quite an easy fix.
